package org.jjppp.tools.typecheck;

import org.jjppp.parser.SysYBaseVisitor;
import org.jjppp.type.Type;

/**
 * TypeChecker type checks the **Original AST**
 * generated by ANTLR. Thus extends `SysYBaseVisitor`
 */
public final class TypeChecker extends SysYBaseVisitor<Type> {
}
